// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { PrismaClient } from '@prisma/client';

export const prisma = new PrismaClient({
  adapter: {
    url: 'postgresql://postgres:YOUR_PASSWORD@localhost:5432/market',
  },
});
